### PR TITLE
Prevent sending ETW within a lock

### PR DESCRIPTION
**Pull request by lifengl**
This code amplifies ETW trace costs, and makes them into thread pool issues in some traces which leads to more noises in performance tests.

### CODE REVIEW

**Review by AArnott — APPROVED** [review]

**Comment by drewnoakes** [comment]
Could this end up with events appearing in incorrect order via ETW, and would that be an issue?

**Comment by lifengl** [comment]
it looks like the optProf data is out of dated in this repo.  Maybe OptProf run stops working in this repo? I will rerun it to see whether it can be resolved.  @AArnott

**Comment by AArnott** [comment]
@lifengl, this repo had been having optprof run problems recently, but I fixed them recently, and we've had a few insertions in the last week. 
I think the failures you're seeing are all related to v16.10, which _is_ still broken. But that shouldn't impact this PR or our main branch.

**Comment by lifengl** [comment]
> @lifengl, this repo had been having optprof run problems recently, but I fixed them recently, and we've had a few insertions in the last week. I think the failures you're seeing are all related to v16.10, which _is_ still broken. But that shouldn't impact this PR or our main branch.

it somehow blocks this PR to be merged. Maybe this one is created earlier so builds in 17.6 are not excluded?

**Comment by AArnott** [comment]
@lifengl now it isn't optprof, but loc that is breaking the official build. I have #1156 that I believe will resolve it.

**Pull request merged**
