### PR TITLE
Add CompilationEnd tag to VSTHRD010 analyzer

### LINKED ISSUE #1113: Add WellKnownDiagnosticTags.CompilationEnd for compilation end diagnostic descriptors
#### Bug description
`DiagnosticDescriptor` for diagnostics reported in compilation end action should have `WellKnownDiagnosticTags.CompilationEnd`. See https://github.com/dotnet/roslyn/issues/65304#issuecomment-1309882140 for details.

#### Repro steps
See https://github.com/dotnet/roslyn/issues/65304 for details.

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #1113

### CODE REVIEW

**Review by mavasani — APPROVED** [review]
LGTM

Is this the only analyzer that has compilation end diagnostics?

**Comment by AArnott** [comment]
Yes it is, @mavasani. Thank you for your review.

**Comment by mavasani** [comment]
@AArnott This was reported by a customer in https://developercommunity.visualstudio.com/t/Error-List-warnings-disappears-when-file/10235352. Can you please update that feedback ticket with information about newer analyzer NuGet package with this fix?

**Comment by AArnott** [comment]
Done, @mavasani.

**Pull request merged**
