### PR TITLE
Avoid `Tuple` allocation in `ToTask(WaitHandle)` when `CancellationToken` cannot be cancelled

### PR DESCRIPTION
**Pull request by AArnott**
Thanks to @jdrobison for reviewing the code and drawing my attention to this.

### CODE REVIEW

**Review by jdrobison — APPROVED** [review]

**Review by lifengl — APPROVED** [review]
changes look good to me.

One minor thing is that the comments between 472, 473 leads a little bit confusion, because the next block now registers the cancellation token along with chains a clean-up task. Especially now the clean-up logic is far away (only after the large cancellation registration block), it is easier to lead reader to think the connection between clean-up and the cancellation token registration, which can be quite confusing.  Maybe consider to move just above the clean-up task continuation block?

**Comment by AArnott** [comment]
Thanks for your review, @lifengl. I don't yet understand what's confusing about the code change.

> Maybe consider to move just above the clean-up task continuation block?

What should I move above the cleanup continuation block? I have two cleanup continuations. One only cleans up the `RegisteredWaitHandle` and one cleans that up plus the `CancellationTokenRegistration` that appears directly above it.

**Comment by drewnoakes** [comment]
I'm not familiar with the code here, but could a value tuple be used to avoid the heap allocation altogether?

**Comment by lifengl** [comment]
No, ValueTuple will lead more allocation during the box operation when it is covered to object.

Sent from my phone

On Nov 8, 2021, at 8:00 PM, Drew Noakes ***@***.***> wrote:

﻿

I'm not familiar with the code here, but could a value tuple be used to avoid the heap allocation altogether?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvs-threading%2Fpull%2F949%23issuecomment-963794668&data=04%7C01%7C%7C0e8ef5fa83c0415239e408d9a3356656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637720272017846909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=N1Uihaxs0Ja9Zu7SChe%2F1qFyTMbW%2BUQdltIdz9U7DnQ%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYZNQS7R2B6JWRGIDIYJE3ULCMD5ANCNFSM5HPBBBWQ&data=04%7C01%7C%7C0e8ef5fa83c0415239e408d9a3356656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637720272017856905%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MRPNwDOOEqMAh7O3npAsu4vvIX5cI64BWChNvCdSPD8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C0e8ef5fa83c0415239e408d9a3356656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637720272017856905%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dHPioTi%2BMK5ZWejFQkOzrUrWGz0fmxq%2B1PMzEt8gWcc%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C0e8ef5fa83c0415239e408d9a3356656%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637720272017866899%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9ptMsFJ4C7F9oqSQ5sq3cy8PYPFpwUL3A5lBV836uYU%3D&reserved=0>.

**Comment by lifengl** [comment]
Well, the comments above the condition check reads like to describe the function of the entire block blow. Basically we want to do cleanup under both conditions, which is exactly what it is before this change.

After this change, the top 10 lines of the first condition is to chain the cancellation token which is not related to the cleanup mentioned in the comments. It is only further reading of the code the comments start to make sense. I think it should be moved closer to the code really related to it.

Sent from my phone

On Nov 8, 2021, at 7:36 AM, Andrew Arnott ***@***.***> wrote:

﻿

Thanks for your review, @lifengl<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flifengl&data=04%7C01%7C%7C04743f91e5c34533e18008d9a2cd8c89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637719825973761979%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Jw97NU1R35o9H4fTZOmrXupX3koLlUrqaTWcW1OBK2E%3D&reserved=0>. I don't yet understand what's confusing about the code change.

Maybe consider to move just above the clean-up task continuation block?

What should I move above the cleanup continuation block? I have two cleanup continuations. One only cleans up the RegisteredWaitHandle and one cleans that up plus the CancellationTokenRegistration that appears directly above it.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fvs-threading%2Fpull%2F949%23issuecomment-963279273&data=04%7C01%7C%7C04743f91e5c34533e18008d9a2cd8c89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637719825973771976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vEtP2OxtjnVtxJcSsSMyuAerZz81ea9ktot%2FpRcuXn0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACYZNQVRJYENGC5YMV2BJXDUK7VAHANCNFSM5HPBBBWQ&data=04%7C01%7C%7C04743f91e5c34533e18008d9a2cd8c89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637719825973771976%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cTT1ChVem%2BAfWj9MjgOEMwLERQWTY2NP21FQ%2Bfidivs%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C04743f91e5c34533e18008d9a2cd8c89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637719825973781972%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=e3xVrbMo%2BElb6XpsYgL8KtppfhcVGNZraXQ04yfmF%2BE%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C04743f91e5c34533e18008d9a2cd8c89%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637719825973791966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=L9DqYo8vJA8RzmAdm9ozzxbdRBzyjXPKMqfzigCeERQ%3D&reserved=0>.

**Comment by AArnott** [comment]
I see now. Thank you, @lifengl.

**Pull request merged**
