### PR TITLE
Use `ManualResetEvent` on `AwaitExtensions.WaitForRegistryChangeAsync`.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
There is no point in using `ManualResetEventSlim` if we want to only get its `WaitHandle`.

### CODE REVIEW

**Comment by AArnott** [comment]
I suspect you're probably right, but unless this actually improves perf or fixes a bug, I would rather not change the method as virtually any change presents some risk, and I'd rather spend that on things that add significant value.

Thank you for offering though.

**Comment by teo-tsirpanis** [comment]
Hello, you could say it improves performance by saving one allocation; we create only an MRE instead of an MRES from which we only get its `WaitHandle`.

I also saved another allocation and reduced indirection by eliminating the closure on Windows 8+, while taking care that the codebase is minimally changed.

**Comment by teo-tsirpanis** [comment]
CI failures on macOS are unrelated.

**Review by AArnott — APPROVED** [review]
Thank you.

**Review by lifengl — APPROVED** [review]
looks good to me.

**Pull request merged**
