### PR TITLE
Add test for field awaited in JTF run delegate

### LINKED ISSUE #254: VSTHRD003 should flag awaiting Task from fields
The following does not produce a diagnostic from VSTHRD003:

```cs
class Program
{
    static Task t;
    static JoinableTaskFactory jtf;

    static void Main(string[] args)
    {
        jtf.Run(async delegate
        {
            await t;
        });
    }
}
```

It seems VSTHRD003 only triggers when the `Task` is a local variable.

### PR DESCRIPTION
**Pull request by sharwell**
Closes #254

### CODE REVIEW

**Comment by sharwell** [comment]
@AArnott rebase and retarget complete

**Comment by AArnott** [comment]
Thanks. Evidently the master branch had some test enhancements that 15.8 lacks, and the compile break is real. We can just take this to master to avoid you having to rewrite.

**Comment by AArnott** [comment]
Rats. There are merge conflicts. Can you resolve this? You can go either way (fix up the v15.8 build break or fix the merge conflict with master). Thanks.

**Comment by sharwell** [comment]
I'll figure this out tonight. It's no rush since it was just an added test. 😄

**Comment by sharwell** [comment]
This was fixed in #308, so I am moving the PR back to target **master**.

**Comment by sharwell** [comment]
@AArnott rebased again 😄

**Pull request merged**
