### PR TITLE
Improve performance of VSTHRD003 analyzer

### LINKED ISSUE #567: VSTHRD003UseJtfRunAsyncAnalyzer causes performance issues when running on a project with nullable analysis enabled
#### Bug description
https://github.com/microsoft/vs-threading/commit/d385b692c3714f0b2a3f2b6bc23c7974389d7627 introduced a change that causes VSTHRD003 to not use the cached semantic model when attempting to look up information. When nullability analysis is enabled, this means that every time this analyzer requests semantic information, the entire member body will be rebound and reanalyzed by Roslyn. @davkean noticed this when working in dotnet/project-system, and subsequent analysis of a trace he took (`\\mlangfs1\public\davkean\Threading\PerfViewData.etl.zip`) narrowed it down to this analyzer. Based on a quick reading of the analyzer, it appears like this will be done for every `await`, `return`, and lambda in the method, meaning that binding and analysis could be done many times over. A quick fix would be to first have the two locations in this analyzer that call `GetSemanticModel` only get a new semantic model if necessary, but a better fix would be only use the model from the appropriate context, as we've already done binding/analysis and cached the results for these models.

image

### PR DESCRIPTION
**Pull request by AArnott**
Fixes #567

### CODE REVIEW

**Comment by AArnott** [comment]
@333fred can you confirm that this should fix the bug you filed?

**Comment by 333fred** [comment]
Looking at the code it seems correct and like it should solve a lot of the issue. The question will be how often the analyzer needs to look at nodes that are not from the original syntax tree. Do you have an idea of how often that can happen?

It might also be helpful if you can send a drop to @davkean so he can see if it makes his experience better.

**Comment by davkean** [comment]
I saw this in the CPS code base, as soon as you have a new version published I can move them forward to it.

**Comment by AArnott** [comment]
Thanks. We'll optimistically complete then.
As far as @333fred's question about how frequently this comes up: not often. The bug where we threw an exception in this case lived a long time before being detected.

**Comment by AArnott** [comment]
@davkean: Please upgrade the CPS code base to [16.4.36](https://dev.azure.com/azure-public/vside/_packaging?_a=package&feed=vssdk&package=Microsoft.VisualStudio.Threading.Analyzers&protocolType=NuGet&version=16.4.36&view=overview) and let me know how that improves things. If the fix worked, I'll push the package to nuget.org.

**Comment by davkean** [comment]
I ran into https://github.com/microsoft/vs-threading/issues/573 when I upgraded, so held off.

**Pull request merged**
