### PR TITLE
Handle IAsyncEnumerable and ValueTask returning methods in VSTHRD103

### LINKED ISSUE #633: VSTHRD103: Analyzer unable to detect synchronous wait call in asynchronous function that returns IAsyncEnumerable
#### Bug description
Analyzer rule VSTHRD002 is unable to detect synchronous wait call in in asynchronous function that returns IAsyncEnumerable.

#### Repro steps
Use below code snippet:
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace vsthreadtest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            await foreach(var i in FooAsync())
            {
                Console.WriteLine(i);
            }
        }

        public static async IAsyncEnumerable<int> FooAsync()
        {
            await Task.Delay(TimeSpan.FromSeconds(5));
            foreach (int i in Enumerable.Range(1, 10))
            {
                Task.Delay(TimeSpan.FromSeconds(5)).Wait();
                yield return i;
            }
        }

        public static IEnumerable<int> Foo()
        {
            foreach (int i in Enumerable.Range(1, 10))
            {
                Task.Delay(TimeSpan.FromSeconds(5)).Wait();
                yield return i;
            }
        }
    }
}
```

#### Expected behavior
All the Task.Delay(TimeSpan.FromSeconds(5)).Wait() calls will be detected.

#### Actual behavior
Task.Delay(TimeSpan.FromSeconds(5)).Wait() in FooAsync is not detected by VSTHRD002.
image
.

- Version used: "Microsoft.VisualStudio.Threading.Analyzers 16.6.13"
- Application (if applicable): 

#### Additional context
I only test the behavior of application targeted "netcoreapp3.1".

### PR DESCRIPTION
**Pull request by cezarypiatek**
I think this might fix #633

### CODE REVIEW

**Comment by AArnott** [comment]
@cezarypiatek  How would a change to VSTHRD103 fix a bug in VSTHRD002?

**Comment by AArnott** [comment]
Ah, I see. #633 incorrectly believes that VSTHRD002 would report the diagnostic, but really it is VSTHRD103's responsibility. :)

**Review by AArnott — APPROVED** [review]
The fix looks good. I've written a test to repro #633 and a ValueTask returning variant of it, as this PR suggests. The test change led to a regression in another test, so I'm working to fix that, then I will merge this PR. Thank you!

**Comment by cezarypiatek** [comment]
Thanks for merging

**Pull request merged**
